linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unparam
    - unused
    - varcheck
